version: 2.1

jobs:
  python-job:
    docker:
      - image: circleci/python:3.10.1-node-browsers
    steps:
      - checkout
      - run:
          name: Create virtual environment
          command: python -m venv venv
      - run:
          name: Install dependencies from requirements.txt
          command: |
            ./venv/bin/pip install --upgrade pip
            ./venv/bin/pip install -r requirements.txt
            ./venv/bin/pip install pytest pytest-html requests
            
      - run:
          name: Run tests with HTML report
          command: ./venv/bin/pytest --html=report.html --self-contained-html
      - store_artifacts:
          path: report.html
          destination: python-report

workflows:
  build-and-test:
    jobs:
      - python-job
